"""
Request and Response Models for Chat API

This module defines Pydantic models for all REST API endpoints.
"""

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field, field_validator


class TokenUsage(BaseModel):
    """Token usage information for LLM calls"""
    
    input_tokens: int = Field(
        default=0,
        description="Total input tokens used in this conversation"
    )
    output_tokens: int = Field(
        default=0,
        description="Total output tokens generated in this conversation"
    )
    total_tokens: int = Field(
        default=0,
        description="Total tokens (input + output)"
    )
    
    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "input_tokens": 1250,
                    "output_tokens": 420,
                    "total_tokens": 1670
                }
            ]
        }
    }


# =============================================================================
# Image / File Attachments
# =============================================================================

# Maximum total payload size for attachments (20 MB)
MAX_ATTACHMENT_SIZE_BYTES = 20 * 1024 * 1024

# Allowed MIME types for attachments (images + documents)
ALLOWED_ATTACHMENT_TYPES = {
    "image/png",
    "image/jpeg",
    "image/jpg",
    "image/gif",
    "image/webp",
    "application/pdf",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",  # .docx
}

# Convenience alias for backward compatibility
ALLOWED_IMAGE_TYPES = ALLOWED_ATTACHMENT_TYPES


class ImageAttachment(BaseModel):
    """A file attachment sent alongside a chat message.
    
    Supports images (png, jpeg, gif, webp) and documents (pdf, docx).
    The file data is base64-encoded and sent inline in the JSON body.
    For the multipart/form-data upload endpoint the backend converts
    the uploaded file into this format internally.
    """
    
    media_type: str = Field(
        ...,
        description="MIME type of the attachment (e.g. image/png, application/pdf)"
    )
    data: str = Field(
        ...,
        description="Base64-encoded file data (no data-URI prefix)"
    )
    filename: Optional[str] = Field(
        default=None,
        description="Original filename (for display purposes only)"
    )
    
    @property
    def is_pdf(self) -> bool:
        return self.media_type == "application/pdf"
    
    @property
    def is_docx(self) -> bool:
        return self.media_type == "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    
    @property
    def is_document(self) -> bool:
        return self.is_pdf or self.is_docx
    
    @property
    def is_image(self) -> bool:
        return self.media_type.startswith("image/")
    
    @field_validator("media_type")
    @classmethod
    def validate_media_type(cls, v: str) -> str:
        if v not in ALLOWED_ATTACHMENT_TYPES:
            raise ValueError(
                f"Unsupported attachment type '{v}'. "
                f"Allowed: {', '.join(sorted(ALLOWED_ATTACHMENT_TYPES))}"
            )
        return v
    
    @field_validator("data")
    @classmethod
    def validate_data_not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Image data cannot be empty")
        return v.strip()


class ChatRequest(BaseModel):
    """Request model for sending a chat message"""
    
    conversation_id: str = Field(
        ...,
        description="Conversation ID generated by the client. Must be provided for both new and existing conversations."
    )
    message: str = Field(
        ...,
        min_length=1,
        max_length=10000,
        description="User message to send to the assistant"
    )
    attachments: Optional[List[ImageAttachment]] = Field(
        default=None,
        description="Optional list of image attachments to include with the message"
    )
    metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional metadata for the message (e.g., user info, session data)"
    )
    
    @field_validator('message')
    @classmethod
    def validate_message(cls, v: str) -> str:
        """Ensure message is not just whitespace"""
        if not v.strip():
            raise ValueError("Message cannot be empty or whitespace only")
        return v.strip()
    
    @field_validator('attachments')
    @classmethod
    def validate_attachments(cls, v):
        """Limit number of attachments and total size."""
        if v is None:
            return v
        if len(v) > 5:
            raise ValueError("Maximum 5 attachments per message")
        # Rough size check (base64 is ~4/3 of raw bytes)
        import base64
        total_bytes = 0
        for att in v:
            try:
                total_bytes += len(base64.b64decode(att.data))
            except Exception:
                raise ValueError(f"Invalid base64 data for attachment '{att.filename}'")
        if total_bytes > MAX_ATTACHMENT_SIZE_BYTES:
            raise ValueError(
                f"Total attachment size ({total_bytes / 1024 / 1024:.1f} MB) "
                f"exceeds limit ({MAX_ATTACHMENT_SIZE_BYTES / 1024 / 1024:.0f} MB)"
            )
        return v
    
    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "conversation_id": "conv_a1b2c3d4e5f6g7h8",
                    "message": "What tools are available?"
                },
                {
                    "conversation_id": "conv_123abc456def789a",
                    "message": "Analyze this P&ID diagram",
                    "attachments": [
                        {
                            "media_type": "image/png",
                            "data": "<base64-encoded-image>",
                            "filename": "pfd_diagram.png"
                        }
                    ],
                    "metadata": {"user_id": "user_456"}
                }
            ]
        }
    }


class EditMessageRequest(BaseModel):
    """Request model for editing a previously sent user message.
    
    Truncates the conversation from the specified message index onward
    and re-processes with the new content.
    """
    
    message_index: int = Field(
        ...,
        ge=0,
        description="Zero-based index of the user message to edit in the conversation history"
    )
    new_content: str = Field(
        ...,
        min_length=1,
        max_length=10000,
        description="The edited message content to replace the original"
    )
    attachments: Optional[List[ImageAttachment]] = Field(
        default=None,
        description="Optional list of attachments to include with the edited message"
    )
    metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional metadata (e.g., user_id for tracking)"
    )

    @field_validator('new_content')
    @classmethod
    def validate_new_content(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Edited message cannot be empty or whitespace only")
        return v.strip()
    
    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "message_index": 2,
                    "new_content": "Design a shell and tube heat exchanger for 500 kW"
                }
            ]
        }
    }


class ToolExecution(BaseModel):
    """Tool execution record for chat response"""
    
    tool_name: str = Field(..., description="Name of the tool executed")
    status: Literal["success", "error"] = Field(..., description="Execution status")
    duration_ms: Optional[int] = Field(default=None, description="Execution time in milliseconds")
    summary: Optional[str] = Field(default=None, description="Brief result summary")
    arguments: Optional[Dict[str, Any]] = Field(default=None, description="Arguments passed to the tool")
    result: Optional[Dict[str, Any]] = Field(default=None, description="Full tool result output")


class ChatResponse(BaseModel):
    """Response model after sending a chat message"""
    
    conversation_id: str = Field(
        ...,
        description="Conversation ID for tracking multi-turn chat"
    )
    request_id: str = Field(
        ...,
        description="Unique request ID for tracking this specific message processing"
    )
    status: Literal["processing", "completed", "error"] = Field(
        ...,
        description="Current status of the request"
    )
    message: Optional[str] = Field(
        default=None,
        description="Optional status message (e.g., error details)"
    )
    token_usage: Optional[TokenUsage] = Field(
        default=None,
        description="Token usage statistics for this conversation"
    )
    run_ids: List[str] = Field(
        default_factory=list,
        description="Array of simulation run IDs (newest first, max 10)"
    )
    tool_executions: List[ToolExecution] = Field(
        default_factory=list,
        description="List of tools executed in this request"
    )
    
    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "conversation_id": "conv_123abc",
                    "request_id": "req_789xyz",
                    "status": "processing"
                },
                {
                    "conversation_id": "conv_123abc",
                    "request_id": "req_789xyz",
                    "status": "completed",
                    "message": "Here are the available tools for sugar processing...",
                    "token_usage": {
                        "input_tokens": 1250,
                        "output_tokens": 420,
                        "total_tokens": 1670
                    }
                }
            ]
        }
    }


class MessageHistoryItem(BaseModel):
    """Single message in conversation history"""
    
    role: Literal["user", "assistant"] = Field(
        ...,
        description="Role of the message sender"
    )
    content: str = Field(
        ...,
        description="Message content"
    )
    timestamp: Optional[datetime] = Field(
        default=None,
        description="When the message was created"
    )
    status: Optional[str] = Field(
        default="complete",
        description="Message status: streaming, complete, error, cancelled"
    )
    message_id: Optional[str] = Field(
        default=None,
        description="Unique message identifier"
    )
    metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional metadata (tool calls, run_id, etc.)"
    )


class ExecutedToolRecord(BaseModel):
    """Record of an executed tool in conversation context"""
    
    tool_name: str = Field(..., description="Name of the tool executed")
    status: Optional[str] = Field(default=None, description="Execution status")
    duration_ms: Optional[int] = Field(default=None, description="Execution time in milliseconds")
    summary: Optional[str] = Field(default=None, description="Brief result summary")
    run_id: Optional[str] = Field(default=None, description="Associated run ID if applicable")


class ConversationContextResponse(BaseModel):
    """Response model for conversation context/state"""
    
    conversation_id: str = Field(
        ...,
        description="The conversation identifier"
    )
    status: str = Field(
        default="idle",
        description="Conversation status: idle, processing, completed, error"
    )
    messages: List[MessageHistoryItem] = Field(
        default_factory=list,
        description="Full message history"
    )
    run_ids: List[str] = Field(
        default_factory=list,
        description="Array of simulation run IDs (newest first, max 10)"
    )
    executed_tools: List[ExecutedToolRecord] = Field(
        default_factory=list,
        description="List of tools that have been executed in this conversation"
    )
    current_industry: Optional[str] = Field(
        default=None,
        description="Currently selected industry (if any)"
    )
    current_process: Optional[str] = Field(
        default=None,
        description="Currently selected process (if any)"
    )
    created_at: datetime = Field(
        ...,
        description="When the conversation was created"
    )
    updated_at: datetime = Field(
        ...,
        description="When the conversation was last updated"
    )
    last_event_sequence: int = Field(
        default=0,
        description="Last event sequence number (for SSE reconnection)"
    )
    is_shared: bool = Field(
        default=False,
        description="Whether the conversation has an active public share link"
    )
    share_url: Optional[str] = Field(
        default=None,
        description="Public share URL if is_shared is True"
    )
    hx_session_id: Optional[str] = Field(
        default=None,
        description="HX Engine session ID for the most recent design run"
    )
    hx_steps: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Raw StepRecord list persisted after design completes (used to restore HX panel on refresh)"
    )
    hx_waiting_for_user: bool = Field(
        default=False,
        description="True when the pipeline is paused waiting for user input (escalation/warning). Used to restore interactive state on page refresh."
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "conversation_id": "conv_123abc",
                    "messages": [
                        {
                            "role": "user",
                            "content": "List available industries",
                            "timestamp": "2026-01-07T10:00:00Z"
                        },
                        {
                            "role": "assistant",
                            "content": "Available industries: sugar, ethanol",
                            "timestamp": "2026-01-07T10:00:02Z",
                            "metadata": {"tool_calls": ["list_industries"]}
                        }
                    ],
                    "run_ids": ["run_abc123"],
                    "executed_tools": ["list_industries"],
                    "current_industry": None,
                    "current_process": None,
                    "created_at": "2026-01-07T10:00:00Z",
                    "updated_at": "2026-01-07T10:00:02Z"
                }
            ]
        }
    }


class ConversationListItem(BaseModel):
    """Summary of a conversation for list view"""

    conversation_id: str = Field(..., description="The conversation identifier")
    title: Optional[str] = Field(default=None, description="Conversation title (first user message)")
    message_count: int = Field(default=0, description="Number of messages in conversation")
    has_simulations: bool = Field(default=False, description="Whether any simulations were run")
    is_shared: bool = Field(default=False, description="Whether the conversation has an active public share link")
    share_url: Optional[str] = Field(default=None, description="Public share URL if is_shared is True")
    created_at: Optional[datetime] = Field(default=None, description="When the conversation was created")
    updated_at: Optional[datetime] = Field(default=None, description="When the conversation was last updated")


class ConversationListResponse(BaseModel):
    """Response model for listing conversations"""
    
    conversations: List[ConversationListItem] = Field(
        default_factory=list,
        description="List of conversations"
    )
    total: int = Field(default=0, description="Total number of conversations")


class ServiceStatus(BaseModel):
    """Status of an individual service"""
    
    name: str = Field(..., description="Service name")
    status: Literal["healthy", "unhealthy", "unknown"] = Field(
        ...,
        description="Health status of the service"
    )
    message: Optional[str] = Field(
        default=None,
        description="Optional status message or error details"
    )
    response_time_ms: Optional[float] = Field(
        default=None,
        description="Response time in milliseconds (if applicable)"
    )


class HealthResponse(BaseModel):
    """Response model for system health check"""
    
    status: Literal["healthy", "degraded", "unhealthy"] = Field(
        ...,
        description="Overall system health status"
    )
    services: Dict[str, ServiceStatus] = Field(
        ...,
        description="Individual service health statuses"
    )
    timestamp: datetime = Field(
        default_factory=datetime.now,
        description="When the health check was performed"
    )
    version: str = Field(
        default="1.0.0",
        description="API version"
    )
    
    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "status": "healthy",
                    "services": {
                        "redis": {
                            "name": "Redis",
                            "status": "healthy",
                            "response_time_ms": 2.5
                        },
                        "mongodb": {
                            "name": "MongoDB",
                            "status": "healthy",
                            "response_time_ms": 5.1
                        },
                        "mcp": {
                            "name": "MCP Server",
                            "status": "healthy",
                            "response_time_ms": 10.3
                        },
                        "llm": {
                            "name": "LLM Provider",
                            "status": "healthy"
                        }
                    },
                    "timestamp": "2026-01-07T10:00:00Z",
                    "version": "1.0.0"
                }
            ]
        }
    }


class ShareResponse(BaseModel):
    """Response after creating a public share link"""

    share_url: str = Field(..., description="Full public URL for the shared design")
    token: str = Field(..., description="Share token (UUID4)")


class HXStep(BaseModel):
    """A single HX pipeline step result stored for sharing"""

    step_id: str = Field(..., description="Step identifier, e.g. BAFFLE_DESIGN")
    step_number: int = Field(..., description="Step number (1-16)")
    status: str = Field(..., description="Step status: APPROVED, CORRECTED, WARNING, ERROR")
    result: Optional[Dict[str, Any]] = Field(default=None, description="Step result payload")
    timestamp: Optional[str] = Field(default=None, description="ISO timestamp when step completed")


class SharedDesignResponse(BaseModel):
    """Public read-only view of a shared design (no auth required)"""

    title: Optional[str] = Field(default=None, description="Design title (first user message)")
    created_at: str = Field(..., description="ISO timestamp when conversation was created")
    messages: List[MessageHistoryItem] = Field(
        default_factory=list,
        description="Full conversation message history"
    )
    hx_steps: List[HXStep] = Field(
        default_factory=list,
        description="HX pipeline step results (empty until HX engine is integrated)"
    )


class ErrorResponse(BaseModel):
    """Standard error response model"""
    
    error: str = Field(
        ...,
        description="Error type or code"
    )
    message: str = Field(
        ...,
        description="Human-readable error message"
    )
    details: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Additional error details"
    )
    conversation_id: Optional[str] = Field(
        default=None,
        description="Conversation ID if applicable"
    )
    request_id: Optional[str] = Field(
        default=None,
        description="Request ID if applicable"
    )
    timestamp: datetime = Field(
        default_factory=datetime.now,
        description="When the error occurred"
    )
    
    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "error": "validation_error",
                    "message": "Message cannot be empty",
                    "timestamp": "2026-01-07T10:00:00Z"
                },
                {
                    "error": "policy_violation",
                    "message": "Cannot simulate without validation",
                    "details": {
                        "required_tool": "validate_process_inputs",
                        "attempted_tool": "simulate_process"
                    },
                    "conversation_id": "conv_123abc",
                    "request_id": "req_789xyz",
                    "timestamp": "2026-01-07T10:00:00Z"
                }
            ]
        }
    }
